title: 전시회 정보를 지도로 한 눈에 - 위대한 쇼맵
url: https://github.com/developduck-studio

enable:
  app_icon: true

device: iphone-15-black

app:
  name: 위대한 쇼맵
  icon: https://is1-ssl.mzstatic.com/image/thumb/Purple211/v4/a5/db/6f/a5db6f59-d229-c269-c397-4c142ef5c527/AppIcon-0-0-1x_U007emarketing-0-10-0-85-220.png/512x512bb.jpg
  ios_id: 6739201841
  android_id: show.greatestmap.app

marketing_header: 전시회 정보를 지도로 한 눈에!
marketing_desc: 가까운 전시회를 찾을 때, 지하철 역 근처 전시회를 찾을 때, 자세한 전시회 정보를 알고 싶을 때 위대한 쇼맵의 지도를 확인하세요.

social-links:
  github: developduck-studio
  blog: developduck-studio
  instagram: greatestshowduck
  email: dev@developduck.studio

social_link_color: black; 
background_color: "#fff8f6"
download_button_text_color: white;
download_button_background_color: "#431104"

version: v1.0
sass:
  style: :compressed

exclude:
  - README.md